-- MySQL Script generated by MySQL Workbench
-- Sun Aug 11 21:50:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teacher` (
  `teacher_id` INT NOT NULL AUTO_INCREMENT,
  `type` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `ability` VARCHAR(45) NULL,
  `adviser` INT NULL,
  `committee` INT NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lockbook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lockbook` (
  `lock_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`lock_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `lockbook_lock_id` INT NOT NULL,
  PRIMARY KEY (`student_id`),
  INDEX `fk_student_lockbook1_idx` (`lockbook_lock_id` ASC),
  CONSTRAINT `fk_student_lockbook1`
    FOREIGN KEY (`lockbook_lock_id`)
    REFERENCES `mydb`.`lockbook` (`lock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`request` (
  `request_id` INT NOT NULL AUTO_INCREMENT,
  `req_1` INT NULL,
  `req_2` VARCHAR(45) NULL,
  `req_3` INT NULL,
  `req_4` INT NULL,
  PRIMARY KEY (`request_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `group_id` INT NOT NULL AUTO_INCREMENT,
  `data` TEXT(65535) NOT NULL,
  `name_project` VARCHAR(100) NOT NULL,
  `info_project` VARCHAR(100) NOT NULL,
  `data_project` TEXT(65535) NOT NULL,
  `check1` VARCHAR(45) NULL,
  `check2` VARCHAR(45) NULL,
  `teacher_teacher_id` INT NOT NULL,
  `student_student_id` INT NOT NULL,
  `request_request_id1` INT NOT NULL,
  PRIMARY KEY (`group_id`),
  INDEX `fk_group_teacher_idx` (`teacher_teacher_id` ASC),
  INDEX `fk_group_student1_idx` (`student_student_id` ASC),
  INDEX `fk_group_request1_idx` (`request_request_id1` ASC),
  CONSTRAINT `fk_group_teacher`
    FOREIGN KEY (`teacher_teacher_id`)
    REFERENCES `mydb`.`teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_request1`
    FOREIGN KEY (`request_request_id1`)
    REFERENCES `mydb`.`request` (`request_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
